import {test,beforeEach} from 'node:test';
import assert from 'node:assert/strict';
import {defaults,Collection,setPath} from './foundry-stub.mjs';
import {D20AgeActorData,D20AgePartyData,D20AgeItemData} from '../scripts/models.mjs';
import {D20AgeActor} from '../scripts/documents.mjs';
import {PACK_PROFILES,cargoState,cargoWeight,assertIncoming,partyCanUse} from '../scripts/party-rules.mjs';
import {executePartyOperation,recoverPartyTransfer,enqueuePartyOperation,registerPartyService,requestPartyOperation} from '../scripts/party-service.mjs';
import {partyView} from '../scripts/party-view.mjs';
let docs,party,mule,pc,other,gm,player,serial;
function patch(doc,data){for(const [key,value]of Object.entries(data)){if(key.includes('.-=')){const parts=key.split('.'),last=parts.pop().slice(2);let parent=doc;for(const part of parts)parent=parent[part];delete parent[last];}else setPath(doc,key,structuredClone(value));}}
function actor(type,name,owners=[]){const a=new D20AgeActor({name,type,system:defaults(type==='party'?D20AgePartyData:D20AgeActorData)});a.id='a'+(++serial);a.uuid='Actor.'+a.id;a.documentName='Actor';a.flags={d20age:{}};a.testUserPermission=(u,p)=>Boolean(u?.isGM||owners.includes(u?.id)||(p==='OBSERVER'&&a.observer));a.update=async data=>{patch(a,data);a.prepareDerivedData();return a;};a.setFlag=(scope,key,v)=>a.update({[`flags.${scope}.${key}`]:v});a.unsetFlag=(scope,key)=>a.update({[`flags.${scope}.-=${key}`]:null});a.createEmbeddedDocuments=async(type,data)=>data.map(x=>{const i=item(x.name,x.system.quantity,x.system.weight);Object.assign(i,structuredClone(x));i.id=x._id??i.id;i.actor=a;a.items.push(i);return i;});a.updateEmbeddedDocuments=async(type,data)=>{for(const x of data)patch(a.items.get(x._id),Object.fromEntries(Object.entries(x).filter(([k])=>k!=='_id')));};a.deleteEmbeddedDocuments=async(type,ids)=>{a.items=new Collection(...a.items.filter(i=>!ids.includes(i.id)));};docs.set(a.uuid,a);a.prepareDerivedData();return a;}
function item(name='Joia',quantity=1,weight=1){const id='i'+(++serial);return {id,name,type:'equipment',img:'x.svg',system:{...defaults(D20AgeItemData),quantity,weight,description:'Somente esta joia.'},toObject(){return {_id:this.id,name:this.name,type:this.type,img:this.img,system:structuredClone(this.system)};}};}
beforeEach(()=>{docs=new Map();serial=0;gm={id:'gm',name:'Mestre',isGM:true};player={id:'p',name:'Jogador',isGM:false};globalThis.fromUuid=async uuid=>docs.get(uuid);foundry.utils={randomID:()=>`r${++serial}`};game.user=gm;game.users=new Collection(gm,player);game.users.activeGM=gm;party=actor('party','Companhia',['p']);mule=actor('creature','Mula');mule.flags.d20age.packAnimal={profile:'mule'};pc=actor('character','Helena',['p']);other=actor('character','Outro');party.system.members=[pc.uuid,other.uuid];party.system.carriers=[mule.uuid];});
beforeEach(()=>{mule.flags.d20age.packParties=[party.uuid];});
const transfer=(source,destination,extra)=>executePartyOperation(party,{action:'transfer',source:source.uuid,destination:destination.uuid,...extra},player);
test('party model has isolated inventory, links and notes without character fields',()=>{const s=defaults(D20AgePartyData);assert.deepEqual(s.members,[]);assert.deepEqual(s.carriers,[]);assert.equal(s.hp,undefined);assert.equal(cargoState(party).max,null);});
test('all six domestic animal thresholds and movement match LB p.120',()=>{for(const [profile,p]of Object.entries(PACK_PROFILES)){mule.flags.d20age.packAnimal={profile};mule.system.coins.gp=p.normal;assert.equal(cargoState(mule).value,p.move);mule.system.coins.gp=p.max;assert.equal(cargoState(mule).value,p.max===p.normal?p.move:p.move/2);mule.system.coins.gp=p.max+1;assert.equal(cargoState(mule).value,0);assert.throws(()=>assertIncoming(mule,1));}});
test('mule includes every coin denomination, saddle, rider and unmarked inventory',()=>{mule.system.coins={cp:10,sp:20,ep:30,gp:40,pp:50};mule.system.extraWeight=1000;const saddle=item('Sela',1,200);saddle.system.carried=false;mule.items.push(saddle);assert.equal(cargoState(mule).weight,1350);assert.equal(cargoState(mule).value,30);});
test('creature derivation uses animal capacity rather than character encumbrance',()=>{mule.system.coins.gp=3500;mule.prepareDerivedData();assert.equal(mule.system.derived.move.value,30);assert.equal(mule.system.derived.move.overloaded,false);assert.deepEqual(mule.system.derived.warnings,[]);});
test('unknown animal must have explicit capacity',()=>{delete mule.flags.d20age.packAnimal;assert.throws(()=>assertIncoming(mule,0),/capacidade/);});
test('split transfer preserves description, debits origin and unequips destination',async()=>{const i=item('Espada',3,100);i.type='weapon';i.system.equipped=true;party.items.push(i);await transfer(party,mule,{item:i.id,quantity:2});assert.equal(i.system.quantity,1);assert.equal(mule.items[0].system.quantity,2);assert.equal(mule.items[0].system.description,i.system.description);assert.equal(mule.items[0].system.equipped,false);assert.equal(party.flags.d20age.partyHistory.length,1);assert.equal(party.flags.d20age.partyTransaction,undefined);});
test('full transfer removes exhausted source stack',async()=>{const i=item();party.items.push(i);await transfer(party,pc,{item:i.id,quantity:1});assert.equal(party.items.length,0);assert.equal(pc.items.length,1);});
test('transfers between animal and own character use real inventory',async()=>{const i=item('Ração',4,20);mule.items.push(i);await transfer(mule,pc,{item:i.id,quantity:3});assert.equal(mule.items[0].system.quantity,1);assert.equal(pc.items[0].system.quantity,3);});
test('exact capacity accepted, next coin refused without debiting origin',async()=>{party.system.coins.gp=4001;await transfer(party,mule,{coin:'gp',quantity:4000});assert.equal(mule.system.coins.gp,4000);await assert.rejects(()=>transfer(party,mule,{coin:'gp',quantity:1}),/capacidade/);assert.equal(party.system.coins.gp,1);});
test('zero, negative, fractional and excess quantities rejected',async()=>{party.system.coins.gp=3;for(const quantity of [0,-1,1.5,NaN,4])await assert.rejects(()=>transfer(party,pc,{coin:'gp',quantity}));assert.equal(party.system.coins.gp,3);});
test('players cannot use other characters, unlinked animals or change capacity',async()=>{assert.equal(partyCanUse(party,other,player),false);await assert.rejects(()=>transfer(other,party,{coin:'gp',quantity:1}),/próprios/);await assert.rejects(()=>executePartyOperation(party,{action:'profile',actor:mule.uuid,profile:'draft'},player),/mestre/);await assert.rejects(()=>executePartyOperation(party,{action:'link',actor:mule.uuid},player),/mestre/);});
test('observers cannot mutate group inventories',async()=>{const observer={id:'observer'};await assert.rejects(()=>executePartyOperation(party,{action:'add-coins',destination:party.uuid,coin:'gp',quantity:1},observer),/permissão/);});
test('serialized competing withdrawals cannot spend the same coins twice',async()=>{party.system.coins.gp=1;const results=await Promise.allSettled([enqueuePartyOperation(()=>transfer(party,pc,{coin:'gp',quantity:1})),enqueuePartyOperation(()=>transfer(party,mule,{coin:'gp',quantity:1}))]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(party.system.coins.gp+pc.system.coins.gp+mule.system.coins.gp,1);});
test('interrupted item transfer is blocked and recoverable without item loss',async()=>{const i=item('Gema',2,50);party.items.push(i);const create=mule.createEmbeddedDocuments;mule.createEmbeddedDocuments=async()=>{throw Error('Disconnected');};await assert.rejects(()=>transfer(party,mule,{item:i.id,quantity:1}),/recuperação/);assert.equal(i.system.quantity,1);assert.ok(party.flags.d20age.partyTransaction);await assert.rejects(()=>transfer(party,pc,{item:i.id,quantity:1}),/interrompida/);mule.createEmbeddedDocuments=create;await recoverPartyTransfer(party,gm);assert.equal(i.system.quantity,2);assert.equal(mule.items.length,0);assert.equal(party.flags.d20age.partyTransaction,undefined);});
test('recovery reverses a credited destination after commit error',async()=>{const i=item('Gema',2,10);party.items.push(i);const update=party.update;party.update=async d=>{if(d['flags.d20age.partyHistory'])throw Error('Commit error');return update(d);};await assert.rejects(()=>transfer(party,mule,{item:i.id,quantity:2}));assert.equal(mule.items.length,1);party.update=update;await recoverPartyTransfer(party,gm);assert.equal(mule.items.length,0);assert.equal(i.system.quantity,2);});
test('coin recovery refuses to overwrite later manual edits',async()=>{party.system.coins.gp=20;const update=mule.update;mule.update=async()=>{throw Error('Offline');};await assert.rejects(()=>transfer(party,mule,{coin:'gp',quantity:5}));mule.update=update;party.system.coins.gp=17;await assert.rejects(()=>recoverPartyTransfer(party,gm),/alterados/);assert.equal(party.system.coins.gp,17);});
test('no active GM fails closed',async()=>{game.users.activeGM=null;await assert.rejects(()=>requestPartyOperation(party,{action:'add-coins'}),/mestre conectado/);});
test('physical loot is validated and animal capacity enforced when adding',async()=>{mule.system.coins.gp=3999;await executePartyOperation(party,{action:'add-item',destination:mule.uuid,name:'Joia',weight:1,quantity:1},player);await assert.rejects(()=>executePartyOperation(party,{action:'add-item',destination:mule.uuid,name:'Outra',weight:1,quantity:1},player),/capacidade/);assert.equal(mule.items.length,1);});
test('unlink keeps original inventory and never deletes linked actor',async()=>{mule.items.push(item());await executePartyOperation(party,{action:'unlink',actor:mule.uuid},gm);assert.equal(party.system.carriers.length,0);assert.equal(mule.items.length,1);assert.equal(docs.has(mule.uuid),true);});
test('group view escapes names, uses live HP and separates reserve from animal cargo',()=>{pc.name='<img onerror=bad>';pc.system.hp.value=8;pc.system.hp.max=12;const html=partyView(party,[pc,mule],{user:player});assert.ok(html.includes('&lt;img onerror=bad&gt;'));assert.ok(html.includes('8/12'));assert.ok(html.includes('não atribuído'));assert.ok(html.includes('4.000'));assert.ok(!html.includes('onerror=bad>'));});
test('document hook uses authenticated sender, not a forged GM payload',async()=>{
 let callback;const original=Hooks.on;Hooks.on=(name,fn)=>{if(name==='updateActor')callback=fn;};registerPartyService();Hooks.on=original;
 foundry.utils.expandObject=x=>x;
 callback(party,{flags:{d20age:{partyRequests:{spoof:{action:'profile',actor:mule.uuid,profile:'draft',userId:'gm'}}}}},{},player.id);
 await enqueuePartyOperation(()=>{});
 assert.equal(mule.flags.d20age.packAnimal.profile,'mule');assert.match(party.flags.d20age.partyResults.spoof.error,/mestre/);
});
test('duplicate queued request is handled once',async()=>{
 let callback;const original=Hooks.on;Hooks.on=(name,fn)=>{if(name==='updateActor')callback=fn;};registerPartyService();Hooks.on=original;foundry.utils.expandObject=x=>x;
 const change={flags:{d20age:{partyRequests:{once:{action:'add-coins',destination:party.uuid,coin:'gp',quantity:5}}}}};
 callback(party,change,{},player.id);callback(party,change,{},player.id);await enqueuePartyOperation(()=>{});assert.equal(party.system.coins.gp,5);
});
test('blocked debit does not create destination treasure',async()=>{const i=item('Joia',3,1);party.items.push(i);party.updateEmbeddedDocuments=async()=>[];await assert.rejects(()=>transfer(party,mule,{item:i.id,quantity:1}),/impedido/);assert.equal(mule.items.length,0);assert.equal(i.system.quantity,3);});
test('a forged party link cannot grant access to a GM-owned animal',async()=>{delete mule.flags.d20age.packParties;assert.equal(partyCanUse(party,mule,player),false);await assert.rejects(()=>transfer(mule,party,{coin:'gp',quantity:1}),/próprios/);});
test('natural attacks of pack animals are not transferable equipment',async()=>{const i=item('1× pata',1,0);i.type='weapon';i.flags={d20age:{source:'d20age RPG - LB (V2)'}};mule.items.push(i);await assert.rejects(()=>transfer(mule,pc,{item:i.id,quantity:1}),/Item não encontrado/);assert.equal(mule.items.length,1);assert.equal(pc.items.length,0);});
