export const GREGORIAN={id:'gregorian',name:'Gregoriano',era:'d.C.',weekdays:['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],months:[['Janeiro',31],['Fevereiro',28],['Março',31],['Abril',30],['Maio',31],['Junho',30],['Julho',31],['Agosto',31],['Setembro',30],['Outubro',31],['Novembro',30],['Dezembro',31]].map(([name,days])=>({name,days})),leap:{every:4,except:100,include:400,month:1,days:1},hoursPerDay:24,minutesPerHour:60,secondsPerMinute:60,weekdayOffset:0};
export function validateCalendar(raw){const d=structuredClone(raw);if(!/^[a-z0-9_-]{1,64}$/.test(d.id)||typeof d.name!=='string'||!d.name.trim()||d.name.length>100)throw Error('Nome ou identificador de calendário inválido.');d.era=String(d.era??'').slice(0,30);if(!Array.isArray(d.months)||!d.months.length||d.months.length>48||!Array.isArray(d.weekdays)||!d.weekdays.length||d.weekdays.length>20)throw Error('Defina meses e dias da semana.');for(const m of d.months)if(!m.name||m.name.length>60||!Number.isInteger(m.days)||m.days<1||m.days>1000)throw Error('Mês inválido.');d.weekdays=d.weekdays.map(n=>String(n).trim());if(d.weekdays.some(n=>!n||n.length>40))throw Error('Dia da semana inválido.');for(const key of ['hoursPerDay','minutesPerHour','secondsPerMinute'])if(!Number.isInteger(d[key])||d[key]<1||d[key]>120)throw Error('Duração do dia inválida.');d.weekdayOffset=Number(d.weekdayOffset??0);if(!Number.isInteger(d.weekdayOffset)||d.weekdayOffset<0||d.weekdayOffset>=d.weekdays.length)throw Error('Dia inicial inválido.');if(d.leap){for(const k of ['every','days'])if(!Number.isInteger(d.leap[k])||d.leap[k]<1||d.leap[k]>1000)throw Error('Regra bissexta inválida.');for(const k of ['except','include'])if(!Number.isInteger(d.leap[k]??0)||(d.leap[k]??0)<0||(d.leap[k]??0)>10000)throw Error('Exceção bissexta inválida.');if(!Number.isInteger(d.leap.month)||!d.months[d.leap.month])throw Error('Mês bissexto inválido.')}return d}
export function leapYear(year,d){const l=d.leap;return !!l&&year%l.every===0&&(!(l.except&&year%l.except===0)||!!(l.include&&year%l.include===0))}
export const monthDays=(year,month,d)=>d.months[month].days+(leapYear(year,d)&&d.leap.month===month?d.leap.days:0);
export const daySeconds=d=>d.hoursPerDay*d.minutesPerHour*d.secondsPerMinute;
function yearDays(year,d){return d.months.reduce((n,_,i)=>n+monthDays(year,i,d),0)}
export function dateToDay({year,month,day},d){if(!Number.isInteger(year)||year<1||year>9999||!Number.isInteger(month)||!d.months[month]||!Number.isInteger(day)||day<1||day>monthDays(year,month,d))throw Error('Data inválida.');let n=0;for(let y=1;y<year;y++)n+=yearDays(y,d);for(let m=0;m<month;m++)n+=monthDays(year,m,d);return n+day-1}
export function dayToDate(n,d){if(!Number.isInteger(n)||n<0)throw Error('Data anterior ao ano 1.');let year=1;while(n>=yearDays(year,d)){n-=yearDays(year++,d);if(year>9999)throw Error('Ano máximo: 9999.')}let month=0;while(n>=monthDays(year,month,d))n-=monthDays(year,month++,d);return {year,month,day:n+1}}
export function dateToSeconds(date,d){const h=Number(date.hour??0),m=Number(date.minute??0),s=Number(date.second??0);if(![h,m,s].every(Number.isInteger)||h<0||h>=d.hoursPerDay||m<0||m>=d.minutesPerHour||s<0||s>=d.secondsPerMinute)throw Error('Horário inválido.');return dateToDay(date,d)*daySeconds(d)+(h*d.minutesPerHour+m)*d.secondsPerMinute+s}
export function secondsToDate(seconds,d){if(!Number.isFinite(seconds)||seconds<0)throw Error('Instante inválido.');const day=Math.floor(seconds/daySeconds(d));let t=Math.floor(seconds%daySeconds(d));const hour=Math.floor(t/(d.minutesPerHour*d.secondsPerMinute));t%=d.minutesPerHour*d.secondsPerMinute;return {...dayToDate(day,d),hour,minute:Math.floor(t/d.secondsPerMinute),second:t%d.secondsPerMinute,weekday:(day+d.weekdayOffset)%d.weekdays.length}}
export function shiftMonth(date,delta,d){let index=(date.year-1)*d.months.length+date.month+delta;if(index<0)throw Error('Data anterior ao ano 1.');const year=Math.floor(index/d.months.length)+1,month=index%d.months.length;return {...date,year,month,day:Math.min(date.day,monthDays(year,month,d))}}
export function currentSeconds(state,worldTime){return state.seconds+(state.linkWorldTime===false?0:worldTime-state.anchor)}
export function calendarCanEdit(user,doc){return !!user&&(user.isGM||!!doc?.testUserPermission?.(user,'OWNER'))}
export function validateEvent(event,d){dateToDay(event,d);if(!event.id||typeof event.title!=='string'||!event.title.trim()||event.title.length>120||String(event.notes??'').length>2000)throw Error('Evento inválido.');return {...event,title:event.title.trim(),notes:String(event.notes??'')}}
