import {LANGUAGE_TABLE,defaultLanguages,ALIGNMENTS,languageLabel} from './languages.mjs';
import {formattedMeasure} from './preferences.mjs';
import {CLASSES,ATTRIBUTES,ATTRIBUTE_ABBR,modifier,signed} from './rules.mjs';
import {GENERATOR_STEPS,CLASS_PROFILES,ANCESTRIES,SKILLS,HIDDEN_SPELLS,IMPLEMENTS,assignedAttributes,cartSummary,budget,hitPoints,buildCharacter,trained} from './generation.mjs';
import {escapeHTML as e} from './view.mjs';
const btn=(label,action,extra='',disabled=false)=>`<button type="button" data-action="${action}" ${extra} ${disabled?'disabled':''}>${label}</button>`;
const options=(rows,current,empty='Escolha…')=>`<option value="">${empty}</option>`+rows.map(([value,label])=>`<option value="${e(value)}" ${String(value)===String(current)?'selected':''}>${e(label)}</option>`).join('');
const genSelect=(label,key,rows,current)=>`<label>${label}<select data-field="${key}">${options(rows,current)}</select></label>`;
const input=(label,key,value,type='text',attrs='')=>`<label>${label}<input data-field="${key}" type="${type}" value="${e(value??'')}" ${attrs}></label>`;
const fmt=n=>Number(n).toLocaleString('pt-BR',{maximumFractionDigits:2});
export function generatorView(d,c,{error='',actor=null,busy=false,image=x=>x}={}){
 const p=CLASS_PROFILES[d.classId],cls=CLASSES[d.classId],attrs=assignedAttributes(d),shopping=cartSummary(d,c.equipment);
 const img=`systems/d20age/assets/classes/${d.classId}.png`;
 let body='';
 if(d.step===0){
  body=`<p class="generator-lead">Escolha quem partirá para a aventura.</p><div class="class-cards">${Object.entries(CLASSES).map(([id,cl])=>{const profile=CLASS_PROFILES[id];return `<button type="button" data-action="choose-class" data-class="${id}" class="class-card ${id===d.classId?'selected':''}" aria-pressed="${id===d.classId}"><img src="${image(`systems/d20age/assets/classes/${id}.png`)}" alt="Ilustração de ${cl.label}"><span class="class-name">${cl.label}</span><span class="class-tag">${profile.tag}</span><span class="class-numbers">d${cl.die}${id==='dwarf'?' +1':''} PV · ${cl.move} pés</span><span class="class-marker">${id===d.classId?'✓ Selecionado':'Escolher classe'}</span></button>`}).join('')}</div><section class="generator-callout"><h3>${cls.label} · ${p.tag}</h3><p>${p.description}</p><p><b>Treinamento:</b> ${p.training}</p><p class="generator-caption">Livro Base V2, p. ${p.page}. Anão, elfo e gnomo são as opções de povos fantásticos.</p></section>`;
 }else if(d.step===1){
  body=`<p class="generator-lead">Seis atributos. Uma história ainda por escrever.</p><div class="generator-modes">${[['ordered','3d6 em ordem','Método do livro'],['distributed','Distribuir 3d6','Opção da mesa'],['manual','Inserir valores','Opção da mesa']].map(([id,label,note])=>btn(`<b>${label}</b><small>${note}</small>`,'method',`data-method="${id}" aria-pressed="${d.method===id}" class="${d.method===id?'selected':''}"`)).join('')}</div>${d.method!=='manual'?`<div class="generator-rollbar">${btn(d.values||d.pool?'Rolar nova série':'Rolar seis vezes 3d6','roll-attributes')}<p>FOR → INT → SAB → DES → CON → CAR (p. 15). Relançamentos seguem o acordo da mesa.</p></div>`:'<p class="generator-caption">Informe resultados rolados fora do Foundry ou definidos pela mesa: 3–18.</p>'}<div class="generator-attributes">${Object.entries(ATTRIBUTES).map(([key,label])=>{const value=attrs?.[key];return `<div class="generator-attribute"><span>${ATTRIBUTE_ABBR[key]}</span><h3>${label}</h3>${d.method==='manual'?`<input aria-label="${label}" type="number" min="3" max="18" step="1" data-attribute="${key}" value="${d.values?.[key]??''}">`:d.method==='distributed'?`<select aria-label="Resultado para ${label}" data-assignment="${key}">${options((d.pool??[]).map((v,i)=>[i,`Dado ${i+1} · ${v}`]),d.assignments[key])}</select>`:`<strong>${value??'—'}</strong>`}<em>Modificador ${value===undefined?'—':signed(modifier(value))}</em></div>`}).join('')}</div>${d.pool?`<div class="generator-pool">Resultados da série: ${d.pool.map((v,i)=>`<span>${i+1} <b>${v}</b></span>`).join('')}</div>`:''}${attrs?`<div class="generator-callout">Soma dos modificadores: <b>${signed(Object.values(attrs).reduce((n,v)=>n+modifier(v),0))}</b>. INT: ${attrs.int<=8?'iletrado':`${Math.max(0,attrs.int-10)} idiomas extras`}. SAB: ${attrs.wis>=16?10:attrs.wis>=13?5:0}% de bônus de XP.</div>`:''}`;
 }else if(d.step===2){
  const weapons=c.equipment.filter(i=>i.type==='weapon'&&trained(d.classId,i)).map(i=>[i.name,i.name]);
  body=`<div class="generator-choice-hero"><img src="${image(img)}" alt="${cls.label}"><div><h2>Os dons de ${cls.label}</h2>${p.abilities.map(([n,t])=>`<details open><summary>${e(n)}</summary><p>${e(t)}</p></details>`).join('')}</div></div><div class="generator-choices">`;
  if(ANCESTRIES[d.classId])body+=`<section>${genSelect('Ancestralidade','ancestry',ANCESTRIES[d.classId].map((t,i)=>[i,`${i+1}. ${t}`]),d.ancestry)}${btn('Sortear ancestralidade · d6','random-ancestry')}<p class="generator-caption">Efeitos condicionais ficam registrados como habilidade; pele-pedra e pés ligeiros são aplicados na ficha.</p></section>`;
  if(['specialist','gnome'].includes(d.classId))body+=`<section>${genSelect('Perícia inicial','skill',Object.keys(SKILLS).map(k=>[k,k]),d.skill)}${btn('Sortear perícia · d10','random-skill')}${d.skill?`<p>${e(SKILLS[d.skill])}</p>`:''}${d.skill==='Arma'?genSelect('Arma da perícia','skillWeapon',weapons,d.skillWeapon):d.skill==='Idioma'?input('Idioma aprendido','skillLanguage',d.skillLanguage):''}</section>`;
  if(d.classId==='fighter')body+=`<section>${genSelect('Arma especializada · +1 de dano','specialization',weapons,d.specialization)}<p>O bônus será aplicado aos exemplares desta arma comprados no gerador.</p></section>`;
  if(['arcanist','elf'].includes(d.classId)){
   const spell=c.spells.find(i=>i._id===d.spellId);
   body+=`<section>${genSelect('Magia inicial · 1º círculo','spellId',c.spells.filter(i=>i.system.circle===1).map(i=>[i._id,i.name]),d.spellId)}${btn('Sortear magia · d20','random-spell')}${spell?`<details open><summary>${e(spell.name)}</summary><p class="generator-description">${e(spell.system.description)}</p></details>`:''}</section>`;
  }
  if(d.classId==='magist'){
   const spell=c.spells.find(i=>i.name===d.hiddenSpell);
   body+=`<section>${genSelect('Magia oculta','hiddenSpell',HIDDEN_SPELLS.map(n=>[n,n]),d.hiddenSpell)}${btn('Sortear magia oculta · d6','random-hidden')}<p>O nível 1 possui somente o espaço oculto; ela ficará registrada na aba Magias.</p>${spell?`<details open><summary>${e(spell.name)}</summary><p class="generator-description">${e(spell.system.description)}</p></details>`:''}</section>`;
  }
  if(['arcanist','magist'].includes(d.classId))body+=`<section>${genSelect('Implemento arcano inicial','implement',IMPLEMENTS.map(n=>[n,n]),d.implement)}${btn('Sortear implemento · d8','random-implement')}<p>Concedido pela classe. Não é uma varinha ou outro item com cargas.</p></section>`;
  body+='</div>';
 }else if(d.step===3){
  const con=attrs?modifier(attrs.con):0;
  body=`<p class="generator-lead">Vida e provisões para a primeira jornada.</p><div class="generator-resources"><section><h3>Pontos de vida</h3><div class="generator-big-number">${hitPoints(d)??'—'}<small>PV iniciais</small></div><p>1d${cls.die} ${signed(con)} CON${d.classId==='dwarf'?' +1 robustez':''}; mínimo 1.</p>${btn(`Rolar vida · d${cls.die}`,'roll-hp')}${input('Resultado do DV (lance externo)','hpDie',d.hpDie,'number',`min="1" max="${cls.die}" step="1"`)}</section><section><h3>Recursos de aventura</h3><div class="generator-big-number">${budget(d)===null?'—':fmt(budget(d))}<small>peças de ouro</small></div><p>3d6 × 10 po para comprar equipamentos.</p>${genSelect('Método','resourceMethod',[['rolled','3d6 × 10 po · livro'],['manual','Valor manual · opção da mesa']],d.resourceMethod)}${d.resourceMethod==='rolled'?btn('Rolar recursos · 3d6 × 10','roll-gold'):input('Ouro definido pela mesa','manualGold',d.manualGold,'number','min="0" max="100000" step="0.01"')}</section></div>`;
 }else if(d.step===4){
  const search=(d.search??'').toLocaleLowerCase('pt-BR');const category=d.category||'all';
  const docs=c.equipment.filter(i=>(category==='all'||i.type===category)&&(i.name.toLocaleLowerCase('pt-BR').includes(search))&&(!d.onlyTrained||trained(d.classId,i))).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR'));
  body=`<div class="generator-shopping-header"><div><span>Recursos</span><b>${fmt(budget(d)??0)} po</b></div><div><span>Compras</span><b>${fmt(shopping.cost)} po</b></div><div class="${shopping.remaining<0?'over-budget':''}"><span>Restante</span><b>${fmt(shopping.remaining??0)} po</b></div></div><p class="generator-caption">Quantidades são lotes da tabela: “Tochas (3)” compra três tochas. Proteções de gnomo têm metade do peso; o preço permanece igual.</p><div class="generator-shop-tools">${input('Buscar equipamento','search',d.search??'','search')}${genSelect('Categoria','category',[['all','Todas'],['weapon','Armas'],['armor','Proteções'],['equipment','Equipamentos']],category)}<label class="generator-checkbox"><input type="checkbox" data-field="onlyTrained" ${d.onlyTrained?'checked':''}>Somente treinados</label>${btn('Adicionar kit de exploração','starter-kit')}</div><div class="generator-shop"><div class="generator-store">${docs.map(i=>{const n=d.cart[i._id]??0;return `<article class="generator-product" data-product-id="${e(i._id)}"><button type="button" class="generator-item-image" data-action="open-item" data-id="${e(i._id)}" aria-label="Ler ${e(i.name)}"><img src="${image(i.img)}" alt=""></button><div><h3><button type="button" class="generator-item-name" data-action="open-item" data-id="${e(i._id)}">${e(i.name)}</button></h3><p>${fmt(i.system.price)} po · ${formattedMeasure((i.system.weight??0)*(d.classId==='gnome'&&i.type==='armor'?.5:1),"weight")} ${i.type==='weapon'?'· '+e(i.system.damage):i.type==='armor'?'· '+(i.system.shield?'escudo':'CA '+i.system.ac):''}</p>${trained(d.classId,i)?'':'<span class="generator-caption">Fora do treinamento</span>'}</div><div class="generator-quantity">${btn('−','quantity',`data-id="${i._id}" data-delta="-1" aria-label="Remover ${e(i.name)}"`,!n)}<b>${n}</b>${btn('+','quantity',`data-id="${i._id}" data-delta="1" aria-label="Adicionar ${e(i.name)}"`,n>=99)}</div></article>`}).join('')||'<p>Nenhum equipamento encontrado.</p>'}</div><aside class="generator-cart"><h3>Sua mochila</h3>${shopping.items.map(row=>`<div class="generator-cart-row"><b>${row.quantity} × <button type="button" class="generator-item-name" data-action="open-item" data-id="${e(row.doc._id)}">${e(row.doc.name)}</button></b><span>${fmt(row.doc.system.price*row.quantity)} po</span>${['weapon','armor'].includes(row.doc.type)?`<label><input type="checkbox" data-equip="${row.doc._id}" ${row.equipped?'checked':''}>Equipado</label>`:''}${btn('Remover','remove',`data-id="${row.doc._id}"`)}</div>`).join('')||'<p>Ainda vazia.</p>'}<p>Massa dos itens: <b>${formattedMeasure(shopping.weight,"weight")}</b>. As moedas restantes também pesam na ficha.</p><p class="generator-caption">O kit é uma sugestão de compras: mochila, corda, odre, ração, tochas e pederneira. Seus preços são descontados.</p></aside></div>`;
 }else{
  let result;try{result=buildCharacter({...d,name:d.name||'Aventureiro'},c,{existing:actor})}catch{}
  body=`<div class="generator-review"><img src="${image(img)}" alt="${cls.label}"><div><h2>Seu próximo aventureiro</h2>${input('Nome do personagem','name',d.name,'text','maxlength="120" autocomplete="off"')}${genSelect('Alinhamento','alignment',Object.entries(ALIGNMENTS).filter(([k])=>k),d.alignment)}${input(`Idiomas extras · INT permite ${Math.max(0,(attrs?.int??10)-10)}`,'languages',d.languages,'text','placeholder="Separe por vírgulas"')}<label>Anotações da aventura<textarea data-field="notes" rows="3">${e(d.notes)}</textarea></label><label class="generator-checkbox"><input type="checkbox" data-field="portrait" ${d.portrait?'checked':''}>Usar a ilustração da classe como retrato</label></div></div><section class="generator-callout"><h3>Idiomas · tabela d20 (LB p.55)</h3><p>Idiomas da classe: <b>${defaultLanguages(d.classId).map(e).join(', ')}</b> · Extras por INT: ${Math.max(0,(attrs?.int??10)-10)}. Selecionados: ${(d.chosenLanguages??[]).length}. ${btn('Sortear idioma · d20','random-language')}</p><div class="language-grid">${LANGUAGE_TABLE.map((n,i)=>`<label><input type="checkbox" data-language="${e(n)}" ${(defaultLanguages(d.classId).includes(n)||(d.chosenLanguages??[]).includes(n))?'checked':''} ${defaultLanguages(d.classId).includes(n)?'disabled':''}><span>${i+1}. ${e(languageLabel(n,d.alignment))}</span></label>`).join('')}</div></section><div class="generator-review-stats">${[['Classe',cls.label],['Nível','1'],['Vida',hitPoints(d)??'—'],['CA',result?.derived.ac??'—'],['TAC0',cls.thac0[0]],['Movimento',result?.derived.move.value??cls.move],['Moedas',fmt(shopping.remaining??0)+' po']].map(([n,v])=>`<div><span>${n}</span><b>${e(v)}</b></div>`).join('')}</div><div class="generator-review-attributes">${Object.entries(ATTRIBUTES).map(([k,n])=>`<span>${ATTRIBUTE_ABBR[k]} <b>${attrs?.[k]??'—'}</b> (${attrs?signed(modifier(attrs[k])):'—'})</span>`).join('')}</div><section class="generator-callout"><h3>Escolhas registradas</h3><p>${e([draftChoice(d,c),d.ancestry!==null?ANCESTRIES[d.classId]?.[d.ancestry]:''].filter(Boolean).join(' · ')||'Dons básicos da classe')}</p><p>${shopping.items.map(r=>`${r.quantity} × ${e(r.doc.name)}${r.equipped?' (equipado)':''}`).join(' · ')||'Sem compras'}</p><p>XP 0 · Alinhamento ${e(d.alignment||'não definido')} · Próximo nível: ${cls.xp[1].toLocaleString('pt-BR')} XP.</p></section>${result?.warnings.length?`<div class="generator-alert"><h3>Conferir com a mesa</h3>${result.warnings.map(w=>`<p>${e(w)}</p>`).join('')}</div>`:''}${actor?`<p class="generator-caption">Ao concluir, esta ficha de nível 1 receberá o nome, classe, atributos, PV, moedas, dons e compras acima. Seus registros e retrato personalizado serão mantidos se a opção de retrato estiver desmarcada.</p>`:'<p class="generator-caption">O personagem será criado somente ao concluir. Voltar preserva suas escolhas.</p>'}`;
 }
 return `<div class="generator-paper"><header class="generator-header"><span>D20AGE RPG · LIVRO BASE V2</span><h1>Crônicas de um aventureiro</h1><p>Da primeira escolha à estrada aberta.</p></header><nav class="generator-progress" aria-label="Etapas de criação">${GENERATOR_STEPS.map((n,i)=>btn(`<span>${i+1}</span>${n}`,'step',`data-step="${i}" class="${d.step===i?'active':''}" ${d.step===i?'aria-current="step"':''}`,busy)).join('')}</nav><main class="generator-body"><div class="generator-stage-heading"><span>ETAPA ${d.step+1} DE 6</span><h2>${GENERATOR_STEPS[d.step]}</h2><b>${cls.label}</b></div>${error?`<div class="generator-alert" role="alert">${e(error).replaceAll('\n','<br>')}</div>`:''}${body}</main><footer class="generator-footer">${btn('Cancelar','cancel','',busy)}<span>Escolhas guardadas enquanto a janela estiver aberta</span>${btn('← Voltar','back','',d.step===0||busy)}${btn(d.step===5?(busy?'Criando…':actor?'Aplicar à ficha':'Criar personagem'):'Continuar →',d.step===5?'finish':'next','class="generator-primary"',busy)}</footer></div>`;
}
function draftChoice(d,c){return [d.classId==='fighter'?'Especialização: '+d.specialization:'',['specialist','gnome'].includes(d.classId)&&d.skill?'Perícia: '+d.skill:'',['arcanist','elf'].includes(d.classId)&&d.spellId?'Magia: '+c.spells.find(i=>i._id===d.spellId)?.name:'',d.classId==='magist'&&d.hiddenSpell?'Magia oculta: '+d.hiddenSpell:'', ['arcanist','magist'].includes(d.classId)?'Implemento: '+d.implement:''].filter(Boolean).join(' · ')}
