import {cargoState,PARTY_COINS,physicalItem,partyCanUse} from './party-rules.mjs';
const partyEscape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cn=n=>Number(n??0).toLocaleString('pt-BR',{maximumFractionDigits:2});
const partyButton=(action,label,attrs='')=>`<button type="button" data-action="${action}" ${attrs}>${label}</button>`;
export function partyView(party,actors,{selected=party.uuid,user=game.user,tab='inventory'}={}){
 const e=partyEscape,owner=party.testUserPermission(user,'OWNER'),gm=user.isGM;
 const located=[party,...actors.filter(a=>a?.testUserPermission(user,'OBSERVER')||partyCanUse(party,a,user))];
 const current=located.find(a=>a.uuid===selected)??party,load=cargoState(current),editable=partyCanUse(party,current,user);
 const attrs=a=>`data-actor="${e(a.uuid)}"`;
 const members=party.system.members.map(uuid=>{const a=actors.find(x=>x?.uuid===uuid);if(!a?.testUserPermission(user,'OBSERVER'))return `<article class="party-member"><h3>Personagem indisponível</h3><p>O mestre pode conceder permissão de observador para a consulta.</p>${gm?partyButton('remove-missing','Remover vínculo',`data-actor="${e(uuid)}"`):''}</article>`;
 const d=a.system.derived??{};return `<article class="party-member"><button type="button" class="party-portrait" data-action="open" ${attrs(a)}><img src="${e(a.img)}" alt="Retrato de ${e(a.name)}"></button><div><h3>${e(a.name)}</h3><small>${e(a.system.title||'Aventureiro')} · Nível ${e(a.system.level)}</small><div class="party-statline"><span><b>${e(a.system.hp.value)}/${e(a.system.hp.max)}</b> PV</span><span><b>${e(d.ac)}</b> CA</span><span><b>${e(d.thac0)}</b> TACO</span><span><b>${e(d.move?.value)}</b> MV</span></div><p class="party-small">Carga ${cn(cargoState(a).weight)} / ${cn(cargoState(a).max)} cn${a.system.conditions?.fatigue?' · Fadiga':''}${a.system.conditions?.exhaustion?' · Exaustão '+e(a.system.conditions.exhaustion):''}</p><div class="party-inline">${partyButton('open','Abrir ficha',attrs(a))}${partyButton('location','Pertences',attrs(a))}${owner&&(gm||a.testUserPermission(user,'OWNER'))?partyButton('unlink','Desvincular',attrs(a)):''}</div></div></article>`;}).join('');
 const carriers=party.system.carriers.map(uuid=>{const a=actors.find(x=>x?.uuid===uuid);if(!a)return `<article class="party-animal">Animal indisponível ${gm?partyButton('remove-missing','Remover vínculo',`data-actor="${e(uuid)}"`):''}</article>`;const c=cargoState(a);return `<article class="party-animal ${c.overCapacity?'overfull':''}"><img src="${e(a.img)}" alt=""><div><h3>${e(a.name)}</h3><p>${cn(c.weight)} / ${cn(c.max)} cn · MV ${cn(c.value)}</p><meter min="0" max="${c.max||1}" value="${Math.min(c.weight,c.max||1)}">${cn(c.weight)} cn</meter><small>${e(c.category)} · ${cn(c.free)} cn livres</small><div class="party-inline">${partyButton('location','Ver carga',attrs(a))}${gm?partyButton('profile','Capacidade',attrs(a))+partyButton('unlink','Desvincular',attrs(a)):''}</div></div></article>`;}).join('');
 const itemRows=Array.from(current.items??[]).filter(physicalItem).filter(i=>i.system.quantity>0).map(i=>`<tr><td><button type="button" class="party-item-link" data-action="item" data-item="${e(i.id)}"><img src="${e(i.img)}" alt=""><span>${e(i.name)}${i.system.equipped?' <small>Equipado</small>':''}${i.system.carried===false?' <small>Não transportado</small>':''}</span></button></td><td>${cn(i.system.quantity)}</td><td>${cn(i.system.weight)}</td><td>${cn(i.system.quantity*i.system.weight)}</td><td>${editable?partyButton('transfer','Transferir →',`data-item="${e(i.id)}"`):'Consulta'}</td></tr>`).join('');
 return `<section class="party-paper"><header class="party-header"><img src="systems/d20age/assets/party.svg" alt=""><div><small>D20AGE RPG · DIÁRIO DA COMPANHIA</small>${owner?`<input name="name" value="${e(party.name)}" aria-label="Nome do grupo">`:`<h1>${e(party.name)}</h1>`}<p>Aventureiros, provisões e tesouros na mesma jornada.</p></div>${gm?partyButton('link','+ Vincular ficha'):owner?partyButton('link','+ Meu personagem'):''}</header>
 <section class="party-roster"><h2>Os aventureiros <span>${party.system.members.length}</span></h2><div class="party-members">${members||'<p class="party-empty">Arraste personagens para cá ou use “Vincular ficha”.</p>'}</div></section>
 <nav class="party-tabs">${partyButton('party-section','Inventário & transporte',`data-section="inventory" aria-pressed="${tab==='inventory'}"`)}${partyButton('party-section','Diário do grupo',`data-section="notes" aria-pressed="${tab==='notes'}"`)}${partyButton('party-section','Transferências',`data-section="history" aria-pressed="${tab==='history'}"`)}</nav>
 ${party.flags?.d20age?.partyTransaction?`<aside class="party-warning">Transferência interrompida. Inventários bloqueados até recuperar.${gm?partyButton('recover','Recuperar transferência'):''}</aside>`:''}
 ${tab==='notes'?`<h2>Anotações da companhia</h2><textarea name="system.notes" class="party-notes" ${owner?'':'disabled'} placeholder="Rotas, acordos e objetivos da aventura…">${e(party.system.notes)}</textarea>`:tab==='history'?`<h2>Últimas movimentações</h2><ol class="party-history">${(party.flags?.d20age?.partyHistory??[]).map(h=>`<li><b>${e(h.quantity)} × ${e(h.label)}</b><span>${e(h.from)} → ${e(h.to)}</span><small>${e(h.user)} · ${e(new Date(h.at).toLocaleString('pt-BR'))}</small></li>`).join('')||'<li>Nenhuma transferência realizada.</li>'}</ol>`:`
 <section><div class="party-section-title"><h2>Animais de carga</h2>${gm?partyButton('pack-animals','+ Adicionar animal de carga'):''}</div><div class="party-carriers">${carriers||'<p class="party-empty">Vincule uma criatura e escolha sua capacidade. Mula: 4.000 cn · LB p.120.</p>'}</div></section>
 <div class="party-location-tabs">${located.map(a=>partyButton('location',a===party?'Reserva do grupo':e(a.name),`${attrs(a)} aria-pressed="${a===current}"`)).join('')}</div>
 <section class="party-inventory"><div class="party-section-title"><div><small>ONDE ESTÃO OS PERTENCES</small><h2>${current===party?'Reserva do grupo':e(current.name)}</h2></div><div class="party-load"><strong>${cn(load.weight)}${load.max!==null?' / '+cn(load.max):''} cn</strong><small>${e(load.category)}</small></div></div>
 ${current===party?'<p class="party-hint">Tesouro ainda não atribuído a um carregador. Transfira para um personagem ou animal antes de viajar.</p>':`<p class="party-hint">${cn(load.free)} cn livres. Equipamentos, moedas e carga adicional entram na conta.</p>`}
 <div class="party-coins">${Object.entries(PARTY_COINS).map(([k,label])=>`<div><b>${cn(current.system.coins?.[k])}</b><span>${label}</span>${editable?partyButton('transfer','Mover',`data-coin="${k}" aria-label="Transferir ${label}"`):''}</div>`).join('')}</div>
 <div class="party-toolbar">${editable?partyButton('treasure','+ Novo tesouro')+partyButton('coins','+ Moedas'):''}<small>1 moeda = 1 cn · Clique no nome para ler o item.</small></div>
 <div class="party-table-wrap"><table><thead><tr><th>Item</th><th>Qtd.</th><th>cn/un.</th><th>cn total</th><th>Ação</th></tr></thead><tbody>${itemRows||'<tr><td colspan="5" class="party-empty">Sem itens. Arraste equipamentos de compêndios ou das fichas vinculadas.</td></tr>'}</tbody></table></div></section>`}
 <footer class="party-footer">Carga em moedas (cn) · LB V2, pp.64 e 120 · Transferências sincronizadas pelo mestre conectado.</footer></section>`;
}
