import {escapeHTML as e} from './view.mjs';
import {UNIT_TABLE,DEFAULT_MEASURES,DEFAULT_COMBAT,measures,combatRules,validateMeasures,validateCombat,applyCombatConfiguration,formattedMeasure} from './preferences.mjs';
import {GREGORIAN,validateCalendar,dateToSeconds,currentSeconds,secondsToDate} from './calendar-core.mjs';
import {calendarConfiguration,calendarDocument,calendarContext,refreshCalendars,openCalendarSummary} from './calendar.mjs';
const {ApplicationV2}=foundry.applications.api;
const field=(label,name,value,type='text')=>`<label class="field"><span>${e(label)}</span><input type="${type}" name="${e(name)}" value="${e(value)}"></label>`;
const choose=(label,name,value,choices)=>`<label class="field"><span>${e(label)}</span><select name="${e(name)}">${Object.entries(choices).map(([key,label])=>`<option value="${e(key)}" ${key===String(value)?'selected':''}>${e(label)}</option>`).join('')}</select></label>`;
const check=(label,name,value)=>`<label class="check"><input type="checkbox" name="${e(name)}" ${value?'checked':''}>${e(label)}</label>`;
const button=(label,action,extra='')=>`<button type="button" data-action="${action}" ${extra}>${label}</button>`;
const shell=(title,body)=>`<form class="sheet-paper configuration-paper"><header class="calendar-heading"><span class="eyebrow">D20AGE · CONFIGURAÇÕES DA MESA</span><h1>${title}</h1></header>${body}<footer class="config-footer">${button('Salvar configurações','save')}</footer></form>`;
export class MeasuresConfig extends ApplicationV2{
 static DEFAULT_OPTIONS={classes:['d20age-sheet','d20age-config'],position:{width:620,height:620},window:{title:'D20Age · Medidas',resizable:true}};
 markup(){const p=measures();return shell('Medidas & carga',`<div class="adjust-cards">${Object.entries({distance:'Distâncias e movimento',weight:'Peso e carga',volume:'Volume e capacidade'}).map(([kind,title])=>`<section class="adjust-card"><h3>${title}</h3>${choose('Unidade',kind,p[kind],Object.fromEntries(Object.entries(UNIT_TABLE[kind]).map(([k,v])=>[k,v.label])))}<p class="hint">Exemplo: ${formattedMeasure(kind==='distance'?40:kind==='weight'?100:10,kind)}</p></section>`).join('')}</div><p class="hint">Base do Livro V2: pés e cn (1 cn ≈ 50 g). Capacidades são armazenadas em litros. Alterar a exibição preserva os dados e a carga. Alcances escritos em texto não são convertidos.</p>${button('Aplicar distância à cena atual','scene')}<p class="hint">Converte a escala da grade da cena ativa quando sua unidade é reconhecida (pés ou metros). Outras cenas permanecem como estão.</p>`)}
 async _renderHTML(){const t=document.createElement('template');t.innerHTML=this.markup();return t.content}
 _replaceHTML(result,content){content.replaceChildren(result)}
 async _onRender(context,options){await super._onRender(context,options);this.element.querySelector("form")?.addEventListener("submit",event=>event.preventDefault())}
 async _onClickAction(event,target){event.preventDefault();try{if(!game.user.isGM)throw Error('Somente o mestre configura a mesa.');const data=new FormData(target.closest('form'));const p=validateMeasures(Object.fromEntries(data));if(target.dataset.action==='save'){await game.settings.set('d20age','measures',p);for(const actor of game.actors)actor.sheet?.rendered&&actor.sheet.render({force:true});return this.close()}
 if(target.dataset.action==='scene'){const scene=canvas.scene;if(!scene)throw Error('Abra uma cena primeiro.');const old=/^(ft|feet|pés|pes)$/i.test(scene.grid.units)?'ft':/^(m|metros?)$/i.test(scene.grid.units)?'m':null;if(!old)throw Error('A unidade da cena não é reconhecida. Configure-a na própria cena.');const distance=scene.grid.distance*(p.distance==='m'?.3048:1)/(old==='m'?.3048:1);await scene.update({'grid.distance':distance,'grid.units':p.distance});ui.notifications.info('Distância da cena convertida.')}}catch(err){ui.notifications.error(err.message)}}
}
export class CombatConfig extends MeasuresConfig{
 static DEFAULT_OPTIONS={window:{title:'D20Age · Regras de combate'},position:{width:620,height:680}};
 markup(){const c=combatRules();return shell('Regras de combate',`<div class="adjust-card">${choose('Dado de iniciativa','initiative',c.initiative,{'1d6':'d6 · Livro Base','1d10':'d10 · Variante','1d20':'d20 · Variante'})}${field('Duração da rodada (segundos)','roundSeconds',c.roundSeconds,'number')}${field('Duração do turno de exploração (minutos)','turnMinutes',c.turnMinutes,'number')}${check('20 natural acerta e 1 natural erra automaticamente','naturalRules',c.naturalRules)}${choose('Dano no 20 natural','critical',c.critical,{normal:'Dano normal · sem crítico extra',doubleDice:'Dobrar os dados da arma · variante'})}${choose('Defesa exibida nos ataques','defense',c.defense,{descending:'CA descendente / TAC0',ascending:'CA ascendente / bônus de ataque'})}</div><p class="hint">As variantes alteram as rolagens, sem modificar as estatísticas das fichas. Na variante crítica, o próximo dano da mesma arma após um 20 natural dobra apenas seus dados. Salvaguardas mantêm as regras do livro. A duração da rodada configura o relógio de combate do Foundry; o calendário acompanha o tempo do mundo.</p>`)}
 async _onClickAction(event,target){event.preventDefault();try{if(!game.user.isGM)throw Error('Somente o mestre configura combate.');const f=new FormData(target.closest('form')),c=validateCombat({...Object.fromEntries(f),naturalRules:f.has('naturalRules')});await game.settings.set('d20age','combatRules',c);applyCombatConfiguration();return this.close()}catch(err){ui.notifications.error(err.message)}}
}
export class CalendarConfig extends MeasuresConfig{
 static DEFAULT_OPTIONS={window:{title:'D20Age · Configurar calendário'},position:{width:780,height:900}};
 get draft(){return this._draft??=structuredClone(calendarConfiguration().definitions[0])}
 markup(){const cfg=calendarConfiguration(),d=this.draft,doc=calendarDocument();const calendars={...Object.fromEntries(cfg.definitions.map(x=>[x.id,x.name])),[d.id]:d.name};return shell('Calendário & permissões',`<section class="adjust-card">${choose('Calendário em uso','activeId',cfg.activeId,calendars)}${check('Acompanhar o tempo do mundo','linkWorldTime',doc?.getFlag('d20age','calendarState')?.linkWorldTime!==false)}<p class="hint">Trocar o calendário mantém os segundos decorridos desde o ano 1. Para ajustar ano, data e hora, use o calendário completo.</p></section><section class="adjust-card"><h3>Edição por jogador</h3><p class="hint">Todos podem consultar. Marque cada pessoa autorizada a alterar data, horário e eventos públicos. Definições de calendários continuam restritas ao mestre.</p>${Array.from(game.users).filter(u=>!u.isGM).map(u=>check(u.name,'editor.'+u.id,doc?.testUserPermission(u,'OWNER'))).join('')||'<p class="hint">Nenhum jogador cadastrado.</p>'}</section><section class="adjust-card"><h3>Construtor de calendários</h3>${choose('Calendário para editar','builderId',d.id,{...calendars,[d.id]:d.name})}<div class="calendar-quick">${button('Novo calendário','new')}${button('Adicionar mês','add-month')}${d.id!=='gregorian'?button('Excluir calendário','delete-calendar'):''}</div>${field('Nome','calName',d.name)}${field('Era / sufixo','era',d.era)}${field('Dias da semana (separados por vírgula)','weekdays',d.weekdays.join(', '))}${field('Índice do dia da semana no início (0 = primeiro)','weekdayOffset',d.weekdayOffset,'number')}<div class="calendar-builder-months">${d.months.map((m,i)=>`<div class="calendar-builder-row">${field('Mês '+(i+1),'monthName.'+i,m.name)}${field('Dias','monthDays.'+i,m.days,'number')}${button('Remover','remove-month',`data-index="${i}"`)}</div>`).join('')}</div><div class="calendar-date-fields">${field('Horas por dia','hoursPerDay',d.hoursPerDay,'number')}${field('Minutos por hora','minutesPerHour',d.minutesPerHour,'number')}${field('Segundos por minuto','secondsPerMinute',d.secondsPerMinute,'number')}</div><details><summary>Anos bissextos</summary>${check('Adicionar dias em anos bissextos','leapEnabled',!!d.leap)}${field('A cada N anos','leapEvery',d.leap?.every??4,'number')}${field('Exceto múltiplos de (0 = nenhuma exceção)','leapExcept',d.leap?.except??0,'number')}${field('Incluir múltiplos de (0 = nenhuma inclusão)','leapInclude',d.leap?.include??0,'number')}${choose('Mês que recebe os dias','leapMonth',d.leap?.month??0,Object.fromEntries(d.months.map((m,i)=>[i,m.name])))}${field('Dias adicionais','leapDays',d.leap?.days??1,'number')}</details><p class="hint">O calendário gregoriano é protegido; crie uma cópia para personalizar. Salvar guarda o calendário aberto no construtor.</p></section>`)}
 async _onRender(context,options){await super._onRender(context,options);const builder=this.element.querySelector('[name="builderId"]');if(this.draft.id==='gregorian')builder?.closest('.adjust-card').querySelectorAll('input,select:not([name="builderId"]),button[data-action="add-month"],button[data-action="remove-month"]').forEach(el=>el.disabled=true);builder?.addEventListener('change',event=>{this._draft=structuredClone(calendarConfiguration().definitions.find(d=>d.id===event.target.value)??GREGORIAN);this.render({force:true})})}
 readDraft(f){const n=k=>Number(f.get(k));return validateCalendar({...this.draft,name:String(f.get('calName')),era:String(f.get('era')),weekdays:String(f.get('weekdays')).split(',').map(x=>x.trim()),weekdayOffset:n('weekdayOffset'),months:this.draft.months.map((_,i)=>({name:String(f.get('monthName.'+i)),days:n('monthDays.'+i)})),hoursPerDay:n('hoursPerDay'),minutesPerHour:n('minutesPerHour'),secondsPerMinute:n('secondsPerMinute'),leap:f.has('leapEnabled')?{every:n('leapEvery'),except:n('leapExcept'),include:n('leapInclude'),month:n('leapMonth'),days:n('leapDays')}:null})}
 async _onClickAction(event,target){event.preventDefault();try{if(!game.user.isGM)throw Error('Somente o mestre configura calendários e permissões.');const action=target.dataset.action,f=new FormData(target.closest('form'));if(action==='new'){this._draft={...structuredClone(GREGORIAN),id:'calendar-'+foundry.utils.randomID().toLowerCase(),name:'Novo calendário',era:'',leap:null};return this.render({force:true})}
 if(action==='add-month'||action==='remove-month'){if(this.draft.id==='gregorian')throw Error('Crie um novo calendário para personalizar.');this._draft=this.readDraft(f);if(action==='add-month')this._draft.months.push({name:'Novo mês',days:30});else{if(this._draft.months.length===1)throw Error('O calendário precisa de um mês.');this._draft.months.splice(Number(target.dataset.index),1);if(this._draft.leap)this._draft.leap.month=Math.min(this._draft.leap.month,this._draft.months.length-1)}return this.render({force:true})}
 const cfg=structuredClone(calendarConfiguration());if(action==='delete-calendar'){if(this.draft.id==='gregorian')throw Error('Não é possível excluir o gregoriano.');if(cfg.activeId===this.draft.id)throw Error('Selecione outro calendário ativo antes de excluir.');if(!await foundry.applications.api.DialogV2.confirm({window:{title:'Excluir calendário'},content:'<p>Excluir esta definição? Eventos históricos serão preservados.</p>'}))return;cfg.definitions=cfg.definitions.filter(x=>x.id!==this.draft.id);await game.settings.set('d20age','calendarConfig',cfg);this._draft=null;return this.render({force:true})}
 if(action==='save'){if(this.draft.id!=='gregorian'){const d=this.readDraft(f);const i=cfg.definitions.findIndex(x=>x.id===d.id);if(i<0)cfg.definitions.push(d);else cfg.definitions[i]=d}cfg.activeId=String(f.get('activeId'));const def=cfg.definitions.find(x=>x.id===cfg.activeId);if(!def)throw Error('Calendário ativo inválido.');const doc=calendarDocument();if(!doc)throw Error('Reabra o mundo como mestre para preparar o calendário.');const old=doc.getFlag('d20age','calendarState');secondsToDate(currentSeconds(old,game.time.worldTime),def);const ownership={default:CONST.DOCUMENT_OWNERSHIP_LEVELS.OBSERVER};for(const u of game.users)if(!u.isGM)ownership[u.id]=f.has('editor.'+u.id)?CONST.DOCUMENT_OWNERSHIP_LEVELS.OWNER:CONST.DOCUMENT_OWNERSHIP_LEVELS.OBSERVER;await doc.update({'==ownership':ownership,'flags.d20age.calendarState':{...old,seconds:currentSeconds(old,game.time.worldTime),anchor:game.time.worldTime,linkWorldTime:f.has('linkWorldTime')}});await game.settings.set('d20age','calendarConfig',cfg);refreshCalendars();return this.close()}
 }catch(err){ui.notifications.error(err.message)}}
}
export function registerSystemSettings(){game.settings.register('d20age','measures',{scope:'world',config:false,type:Object,default:DEFAULT_MEASURES,onChange:()=>{for(const doc of [...game.actors,...game.items])if(doc.sheet?.rendered)doc.sheet.render({force:true})}});game.settings.register('d20age','combatRules',{scope:'world',config:false,type:Object,default:DEFAULT_COMBAT,onChange:applyCombatConfiguration});game.settings.register('d20age','calendarConfig',{scope:'world',config:false,type:Object,default:{activeId:'gregorian',definitions:[GREGORIAN]},onChange:refreshCalendars});game.settings.register('d20age','showCalendarHUD',{name:'Exibir calendário resumido ao entrar',hint:'Preferência individual. O calendário também pode ser aberto nas configurações do jogo.',scope:'client',config:true,type:Boolean,default:true});for(const [key,name,label,hint,type] of [['measuresMenu','Medidas, distâncias, volume e peso','Configurar medidas','Escolha as unidades usadas pela mesa.',MeasuresConfig],['combatMenu','Regras de combate','Configurar combate','Iniciativa, durações, acertos naturais e variantes.',CombatConfig],['calendarMenu','Calendário e permissões','Configurar calendário','Escolha calendários, crie meses e autorize jogadores individualmente.',CalendarConfig]])game.settings.registerMenu?.('d20age',key,{name,label,hint,icon:'fas fa-book',type,restricted:true});game.settings.registerMenu?.('d20age','calendarOpen',{name:'Calendário da campanha',label:'Abrir calendário',hint:'Calendário público da mesa.',icon:'fas fa-calendar',type:CalendarOpen,restricted:false});applyCombatConfiguration()}
class CalendarOpen extends ApplicationV2{render(){return openCalendarSummary()}}
