from pathlib import Path
import re,base64
r=Path(__file__).resolve().parents[1];out=r.parent/'output';out.mkdir(exist_ok=True)
def source(name):
 s=(r/'scripts'/name).read_text();s=re.sub(r'^import[^\n]*\n','',s,flags=re.M);return re.sub(r'\bexport (?=(const|function|class)\b)','',s)
code='\n'.join(source(n) for n in ['preferences.mjs','rules.mjs','view.mjs','calendar-core.mjs','calendar-view.mjs'])
code+='''
let definition=structuredClone(GREGORIAN),definitions=[definition],seconds=dateToSeconds({year:2026,month:9,day:3,hour:12},definition),state={events:[]},viewDate=null,selected=null,editEvent=null;
const root=document.querySelector('#calendar-full'),mini=document.querySelector('#calendar-mini');
const editable=()=>document.querySelector('#role').value==='gm'||document.querySelector('#allowed').checked;
const notice=text=>document.querySelector('#notice').textContent=text;
const prefs={measures:structuredClone(DEFAULT_MEASURES),combatRules:structuredClone(DEFAULT_COMBAT)};globalThis.game={settings:{get:(_,key)=>prefs[key]}};
function render(){document.querySelector('#allowed').disabled=document.querySelector('#role').value!=='gm';mini.innerHTML=calendarSummaryView(state,definition,seconds,editable());root.innerHTML=calendarView(state,definition,seconds,{editable:editable(),viewDate,selected,editEvent});root.querySelector('form').addEventListener('submit',e=>e.preventDefault());document.querySelector('#cal-choice').innerHTML=definitions.map(d=>`<option value="${d.id}" ${d.id===definition.id?'selected':''}>${escapeHTML(d.name)}</option>`).join('');document.querySelector('#demo-settings').querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=document.querySelector('#role').value!=='gm');document.querySelector('#demo-measures').innerHTML=Object.entries({distance:'Distância',weight:'Peso',volume:'Volume'}).map(([k,label])=>`<label>${label}<select data-unit="${k}">${Object.entries(UNIT_TABLE[k]).map(([id,v])=>`<option value="${id}" ${prefs.measures[k]===id?'selected':''}>${v.label}</option>`).join('')}</select></label>`).join('')+'<p>40 pés = '+formattedMeasure(40,'distance')+' · 100 cn = '+formattedMeasure(100,'weight')+' · 10 L = '+formattedMeasure(10,'volume')+'</p>';document.querySelector('#demo-measures').querySelectorAll('select').forEach(el=>el.disabled=document.querySelector('#role').value!=='gm')}
async function action(event){const button=event.target.closest('[data-action]');if(!button)return;event.preventDefault();const previousSeconds=seconds;try{const a=button.dataset.action,now=secondsToDate(seconds,definition);if(a==='open'){document.querySelector('#full-wrapper').hidden=false;root.scrollIntoView({behavior:'smooth'});return}if(a==='month'){viewDate=shiftMonth(viewDate??now,Number(button.dataset.delta),definition);render();return}if(a==='today'){viewDate=null;selected=null;editEvent=null;render();return}if(a==='day'){selected={...viewDate??now,day:Number(button.dataset.day)};editEvent=null;render();return}if(!editable())throw Error('Consulta: o mestre precisa autorizar a edição.');if(a==='advance')seconds+=Number(button.dataset.days)*daySeconds(definition);if(a==='round')seconds+=prefs.combatRules.roundSeconds;if(a==='turn')seconds+=(button.dataset.delta==='-1'?-1:1)*prefs.combatRules.turnMinutes*60;if(a==='advance-month')seconds=dateToSeconds(shiftMonth(now,1,definition),definition);if(a==='set-date'){const f=new FormData(button.closest('form'));seconds=dateToSeconds(Object.fromEntries(['year','month','day','hour','minute'].map(k=>[k,Number(f.get(k))])),definition);viewDate=null;selected=null}if(a==='edit-event')editEvent=button.dataset.id;if(a==='cancel-event')editEvent=null;if(a==='save-event'){const f=new FormData(button.closest('form')),record=validateEvent({...selected??now,calendarId:definition.id,id:editEvent??crypto.randomUUID(),title:f.get('eventTitle'),notes:f.get('eventNotes')},definition);state.events=state.events.filter(x=>x.id!==record.id);state.events.push(record);editEvent=null}if(a==='delete-event')state.events=state.events.filter(x=>x.id!==button.dataset.id);secondsToDate(seconds,definition);render();notice('Alteração aplicada somente à demonstração.')}catch(e){seconds=previousSeconds;notice(e.message)}}
root.addEventListener('click',action);mini.addEventListener('click',action);document.querySelector('#role').onchange=render;document.querySelector('#allowed').onchange=render;
document.querySelector('#demo-measures').onchange=event=>{if(document.querySelector('#role').value!=='gm')return;prefs.measures[event.target.dataset.unit]=event.target.value;render()};
document.querySelector('#cal-choice').onchange=event=>{if(document.querySelector('#role').value!=='gm')return;const now=secondsToDate(seconds,definition);definition=definitions.find(d=>d.id===event.target.value);seconds=dateToSeconds({...now,month:Math.min(now.month,definition.months.length-1),day:1,hour:0,minute:0,second:0},definition);viewDate=null;selected=null;render()};
document.querySelector('#create-custom').onclick=()=>{try{if(document.querySelector('#role').value!=='gm')throw Error('Somente o mestre cria calendários.');const f=new FormData(document.querySelector('#custom-form'));const months=String(f.get('months')).split('\\n').filter(l=>l.trim()).map(l=>{const i=l.lastIndexOf(':');return {name:l.slice(0,i).trim(),days:Number(l.slice(i+1))}});const d=validateCalendar({...structuredClone(GREGORIAN),id:'custom-'+crypto.randomUUID(),name:String(f.get('name')),era:String(f.get('era')),weekdays:String(f.get('weekdays')).split(',').map(n=>n.trim()),months,leap:null});definitions.push(d);definition=d;seconds=0;viewDate=null;selected=null;render();notice('Calendário personalizado criado na demonstração.')}catch(e){notice(e.message)}};
document.querySelector('#custom-form').addEventListener('submit',e=>e.preventDefault());
render();
'''
css=(r/'styles/d20age.css').read_text()
def embed(m):
 p=(r/'styles'/m.group(1)).resolve();return 'url("data:'+('image/png' if p.suffix=='.png' else 'image/svg+xml')+';base64,'+base64.b64encode(p.read_bytes()).decode()+'")'
css=re.sub(r'url\("([^"\n]+\.(?:svg|png))"\)',embed,css)
html='''<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>D20Age · Calendário 0.4.4</title><style>CSS body{background:#ddd;margin:0;padding:24px;color:#111;font:14px Georgia,serif}main{max-width:1150px;margin:auto}.demo-toolbar{display:flex;flex-wrap:wrap;gap:16px;align-items:center;background:#fff;border:2px solid #111;padding:14px;margin-bottom:20px}.demo-layout{display:grid;grid-template-columns:320px minmax(0,1fr);gap:22px;align-items:start}.demo-settings{background:#fff;border:3px double #111;padding:20px;margin-bottom:18px}.demo-settings label{display:block;margin:10px 0}.demo-settings input,.demo-settings select,.demo-settings textarea{display:block;width:100%;box-sizing:border-box;padding:7px;background:#fff;color:#111;border:1px solid #111;font:14px Georgia,serif}.demo-settings button{padding:9px;border:2px solid #111;background:#fff;color:#111;cursor:pointer}#notice{min-height:24px;background:#fff;padding:10px;margin-top:12px}#custom-form textarea{min-height:120px}@media(max-width:850px){.demo-layout{grid-template-columns:1fr}}</style></head><body><main><h1>D20Age · Calendário e medidas</h1><p>Prévia independente. Use Mestre/Jogador para experimentar a consulta e a autorização individual. Não altera o seu mundo no Foundry.</p><div class="demo-toolbar"><label>Perfil <select id="role"><option value="gm">Mestre</option><option value="player">Jogador</option></select></label><label><input type="checkbox" id="allowed"> Mestre autoriza este jogador a editar</label></div><div class="demo-layout"><div><div class="d20age-sheet" id="calendar-mini"></div><section class="demo-settings" id="demo-measures"></section></div><div><details class="demo-settings" id="demo-settings"><summary>Calendários · demonstração do construtor</summary><label>Calendário ativo <select id="cal-choice"></select></label><form id="custom-form"><label>Nome <input name="name" value="Calendário da aventura"></label><label>Era <input name="era" value="D.A."></label><label>Dias da semana <input name="weekdays" value="Primeiro, Segundo, Terceiro, Quarto, Quinto"></label><label>Meses: um por linha, nome:dias<textarea name="months">Chuva:30
Bruma:30
Sol:35</textarea></label><button type="button" id="create-custom">Criar calendário personalizado</button></form><p>No Foundry, o construtor completo também permite editar os meses, horas do dia e regras bissextas.</p></details><section id="full-wrapper" hidden><div class="d20age-sheet" id="calendar-full"></div></section></div></div><p id="notice" role="status"></p></main><script type="module">JS</script></body></html>'''.replace('CSS',css).replace('JS</script>',code.replace('</script','<\\/script')+'</script>')
(out/'d20age-calendario-previa.html').write_text(html);print(out/'d20age-calendario-previa.html')
