from pathlib import Path
import re,json,base64
R=Path(__file__).resolve().parents[1];O=R.parent/'output';O.mkdir(exist_ok=True)
def src(name):
 s=(R/'scripts'/name).read_text();s=re.sub(r'^import[^\n]*\n','',s,flags=re.M);return re.sub(r'\bexport (?=(?:const|function|class)\b)','',s)
content={n:json.loads((R/'content'/(n+'.json')).read_text()) for n in ['equipment','spells']}
images={}
for d in [*content['equipment'],*content['spells']]:
 p=R/d['img'].split('systems/d20age/')[1];images[d['img']]='data:image/svg+xml;base64,'+base64.b64encode(p.read_bytes()).decode()
for p in (R/'assets/classes').glob('*.png'):images['systems/d20age/assets/classes/'+p.name]='data:image/png;base64,'+base64.b64encode(p.read_bytes()).decode()
escape=src('view.mjs').split('const e = escapeHTML;')[0]
code=src('languages.mjs')+'\n'+src('preferences.mjs')+'\n'+src('rules.mjs')+'\n'+escape+'\nconst e=escapeHTML;\n'+src('generation.mjs')+'\n'+src('generator-controller.mjs')+'\n'+src('generator-view.mjs')
code+='\nconst content='+json.dumps(content,ensure_ascii=False).replace('<','\\u003c')+';\nconst images='+json.dumps(images)+';\n'
code+='''const app=document.querySelector('#generator');let controller;
const openItem=id=>{const item=content.equipment.find(i=>i._id===id);if(!item)return;const dialog=document.createElement('dialog');dialog.className='generator-item-reader';dialog.innerHTML=`<button type="button" aria-label="Fechar">×</button><h2>${escapeHTML(item.name)}</h2><img src="${images[item.img]}" alt=""><p>${escapeHTML(item.system.price)} po · ${formattedMeasure(item.system.weight??0,'weight')}</p><p style="white-space:pre-wrap">${escapeHTML(item.system.description)}</p>`;dialog.querySelector('button').onclick=()=>dialog.close();dialog.addEventListener('close',()=>dialog.remove());document.body.append(dialog);dialog.showModal()};
const roll=async formula=>{const match=formula.match(/(\\d+)d(\\d+)/);return Array.from({length:Number(match[1])},()=>1+Math.floor(Math.random()*Number(match[2]))).reduce((a,b)=>a+b,0)};
function restart(){controller=new GeneratorController(content,{roll,openItem,render:(draft,context)=>{app.innerHTML=generatorView(draft,content,{...context,image:path=>images[path]??path});controller.bind(app.querySelector('.generator-paper'),{actions:true});if(context.busy)app.querySelectorAll('input,select,textarea,button').forEach(e=>e.disabled=true)},cancel:()=>{app.innerHTML='<div class="preview-complete"><h2>Criação cancelada</h2><p>Nenhuma ficha foi criada.</p><button type="button" id="again">Recomeçar</button></div>';document.querySelector('#again').onclick=restart},finish:async draft=>{const result=buildCharacter(draft,content);app.innerHTML='<div class="preview-complete"><img alt="Classe escolhida" src="'+images[result.data.img]+'"><h2></h2><p>Prévia concluída. No Foundry, esta etapa cria ou preenche a ficha.</p><button type="button" id="export">Baixar ficha JSON</button> <button type="button" id="again">Recomeçar</button></div>';app.querySelector('h2').textContent=result.data.name+' está pronto!';document.querySelector('#again').onclick=restart;document.querySelector('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(result.data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='d20age-personagem.json';a.click();URL.revokeObjectURL(url)};return true}});controller.refresh()}
restart();'''
css=(R/'styles/d20age.css').read_text().split('/* Character creation:')[1];css='/* Character creation:'+css
css+='''body{margin:0;background:#d7d1c5;color:#171716;font-family:Georgia,serif}#generator{width:min(1080px,100%);height:900px;margin:20px auto;border:2px solid #30302d;box-shadow:7px 9px 0 #aaa08c}.preview-notice{max-width:1080px;margin:18px auto;padding:12px 20px;background:#faf7ee;border:1px solid #817966;font:13px/1.5 Arial,sans-serif}.generator-item-reader{max-width:600px;max-height:80vh;overflow:auto;background:#faf7ee;color:#111;border:3px double #222;padding:24px}.generator-item-reader p{text-align:justify;text-justify:inter-word;line-height:1.6;hyphens:auto;overflow-wrap:anywhere}.generator-item-reader>img{width:64px}.generator-item-reader>button{float:right}.preview-complete{text-align:center;background:#f6f3e9;height:100%;padding:65px 20px}.preview-complete img{display:block;width:240px;margin:auto}.preview-complete button{font:16px Georgia,serif;padding:12px;color:#111;background:#fff;border:2px solid #222;cursor:pointer}@media(max-width:760px){#generator{height:1000px;margin:0}.preview-notice{margin:0}}'''
html='<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>D20Age · Gerador de personagens 0.5.1</title><style>'+css+'</style></head><body><p class="preview-notice"><b>PRÉVIA INTERATIVA · 0.5.1</b> · Experimente as seis etapas do gerador. Os dados e as ilustrações estão incorporados. Esta página não está conectada ao Foundry; as rolagens são demonstrativas. O sistema usa os dados nativos do Foundry para rolar em jogo.</p><div id="generator" class="d20age-generator"></div><script type="module">'+code.replace('</script','<\\/script')+'</script></body></html>'
(O/'d20age-gerador-previa.html').write_text(html);print(O/'d20age-gerador-previa.html')
